//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyingTransaction
    {
        public decimal PurchasedTransactionId { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public Nullable<decimal> PurchasedRatePerGram { get; set; }
        public Nullable<System.DateTime> PurchasedDate { get; set; }
        public Nullable<decimal> PurchasedQuantity { get; set; }
        public Nullable<decimal> PurchasedPrice { get; set; }
        public Nullable<decimal> PurchasedTax { get; set; }
        public Nullable<decimal> PurchasedTotalPrice { get; set; }
        public Nullable<decimal> ProductId { get; set; }
    }
}
